name: Release Image

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the container image
      run: docker build . -t html5validator
    - name: Verify validation (HTML, CSS, SVG)
      run: |
        docker run --rm -v $(pwd):/app:ro html5validator html5validator --html tests/fixtures/valid.html
        docker run --rm -v $(pwd):/app:ro html5validator html5validator --css tests/fixtures/valid.css
        docker run --rm -v $(pwd):/app:ro html5validator html5validator --svg tests/fixtures/valid.svg
    - name: Tag the image
      run: |
        docker tag html5validator painless/html5validator:${{ github.ref_name }}
        docker tag html5validator painless/html5validator:latest
    - name: Push the image
      run: |
        docker login docker.io -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
        docker push painless/html5validator --all-tags
        docker logout
